platform :ios, '9.0'

def common_pods
	pod 'FetchedDataSource', :path => '../'

	pod 'CompoundFetchedResultsController'
	pod 'MagicalRecord', :modular_headers => true
	pod 'Reusable'
end

target 'Example' do
	common_pods
end

target 'ExampleTests' do
	common_pods
	pod 'SwiftyMocky'
end
