platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Example' do
	pod 'FetchedDataSource', :path => '../'

	pod 'CompoundFetchedResultsController'
	pod 'MagicalRecord', :modular_headers => true
	pod 'Reusable'
end